### ISSUE TITLE
explicitly pin forks by rev, add comment with differences and PRs to upstream

### ISSUE THREAD

**Issue by flokli** [wireapp/rusty-jwt-tools#53]
I see you use your own custom fork of `biscuit`, `rust-jwt-simple`, `rcgen` and `x509-parser`.

It'd be good if these could be pinned by rev, not tag (especially considering there's no committed `Cargo.lock`), and there'd be a comment on how this differs from upstream.

Playing whack-a-mole with upstream is no fun, rebasing our our changes on top of it in some months because there has been a security fix in the upstream release even less - so we should also try to get our changes sent upstream, and ideally that comment should include a link to the PR, too.

**Comment by istankovic** [comment]
We dropped the use of `rcgen` and `x509-parser` and there's `Cargo.lock` in root now. The intention is to eventually completely drop our forks, but that's easier said than done.
