### ISSUE TITLE
JWK helper to generate thumbprint

### ISSUE THREAD

**Issue by rohan-wire** [wireapp/rusty-jwt-tools#8]
Should be able to generate a JWK thumbprint and the corresponding URI from any JWK.

- JWK Thumbprint algorithm defined in [RFC7638](https://datatracker.ietf.org/doc/rfc7638/)
- JWK Thumbprint URI defined in [RFC9278](https://datatracker.ietf.org/doc/rfc9278/) 

example URI:
`urn:ietf:params:oauth:jwk-thumbprint:sha-256:NzbLsXh8uDCcd-6MNwXF4W_7noWXFZAfHkxZsRGC9Xs`

**Comment by StemCll** [comment]
Hey @rohan-wire, I will give this issue a try. Will create a draft PR with first changes.

**Comment by StemCll** [comment]
Hi @beltram (mentioning you since I see a lot of your activity in this repo),
I've created a [very simple draft](https://github.com/wireapp/rusty-jwt-tools/pull/25) for URI. I haven't dig into the whole project yet, so it might be off related to the project standards.

**Comment by istankovic** [comment]
Closing, as the related PR is already closed and don't currently plan anything in this area.
